RUN_STRINGS = (
    "现在你看到我，现在你又看不到了。" "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "给我回来！",
    "啊啊啊啊啊啊啊啊啊啊！！！！！！！",
    "小心前面的墙！",
    "别把我一个人留在这里！！",
    "有人来追你了！",
    "等一下！",
    "やれやれだぜ",
    "*鸣人跑法已激活*",
    "*祢豆子跑法已激活*",
    "嘿，你要为你刚才做的事负责！",
    "愿胜算永远对你有利。",
    "大家快跑，他们刚扔了个炸弹 💣💣",
    "就这样，他们消失了，再也没有人见过他们。",
    "传说他们还在跑。",
    "再见了，宝贝。",
    "啊，真可惜，我挺喜欢那个的。",
    "就像医生说的……快跑！",
)

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

SLAP_MUKESH_TEMPLATES = (
    "再打我一次我就禁言你。",
    "别再打我了。啊啊啊啊啊啊啊啊！",
    [
        "禁言你一分钟。",  # normal reply
        "别因为你是管理员我禁不了你就打我。啊啊啊啊啊啊啊啊！",  # reply to admin
        "tmute",  # command
        "闭嘴！",
        "肃静！",
    ],
)

SLAP_TEMPLATES = (
    “{user2} 被魔法秒杀了。”,
    “{user2} 因没有被摸头而饿死了。”,
    “{user2} 被 {user1} 打入虚空。”,
    “{user2} 昏倒了。”,
    “{user2} 的宝可梦全灭了！{user2} 溜出了比赛！”,
    “{user2} 的宝可梦全灭了！{user2} 跑路了！”,
    “{user2} 被虐了。”,
    “{user2} 的西瓜被 {user1} 劈开了。”,
    “{user2} 被 {user1} 切片加工了。”,
    “{user2} 玩起了手榴弹热土豆。”,
    “{user2} 被 {user1} 捅了。”,
    “{user2} 吃了一颗手榴弹。”,
    “{user2} 成了今晚的晚餐！”,
    “{user2} 被 {user1} 终结了。”,
    “{user1} 把 {user2} 的邮箱给轰炸了。”,
    “{user1} 对 {user2} 进行了 RSA 加密并删除了私钥。”,
    “{user1} 把 {user2} 塞进了友情区。”,
    “{user1} 用 DMCA 下架通知打了 {user2}！”,
    “{user2} 被 {user1} 医生上门出诊了。”,
    “{user1} 砍掉了 {user2} 的头。”,
    “{user2} 被愤怒的人群用石头砸了。”,
    “{user1} 把 {user2} 告上了法庭。”,
    “{user2} 被 {user1} 一击必杀。”,
    “{user1} 把 {user2} 送进了记忆黑洞。”,
    “{user2} 是个错误。——‘{user1}’”,
    “{user2} 被裁员了。”,
    “{user1} 用球棒 {hits} 了 {user2}！”,
    “{user1} 用体术踢 {hits} 了 {user2}！”,
    “{user1} 用X手套 {hits} 了 {user2}！”,
    “{user1} 用喷射拳 {hits} 了 {user2}！”,
    “{user1} 用喷射手枪 {hits} 了 {user2}！”,
    “{user1} 用美国无双 {hits} 了 {user2}！”,
    “{user1} 用底特律无双 {hits} 了 {user2}！”,
    “{user1} 用德克萨斯无双 {hits} 了 {user2}！”,
    “{user1} 用加利福尼亚无双 {hits} 了 {user2}！”,
    “{user1} 用新罕布什尔无双 {hits} 了 {user2}！”,
    “{user1} 用密苏里无双 {hits} 了 {user2}！”,
    “{user1} 用卡罗来纳无双 {hits} 了 {user2}！”,
    “{user1} 用金刚枪 {hits} 了 {user2}！”,
    “{user1} 用金属棒 {hits} 了 {user2}！”,
    “*认真地揍了 {user2}*。”,
    “*普通地揍了 {user2}*。”,
    “*连续普通地揍了 {user2}*。”,
    “*双手连续普通地揍了 {user2}*。”,
    “*无视 {user2}，让他们在尴尬中自灭*。”,
    “*指着 {user2}* 这个臭屁的迷路孩子是怎么回事？”,
    “*用火焰龙卷风揍了 {user2}*。”,
    “{user1} 戳了 {user2} 的眼睛！”,
    “{user1} 戳了 {user2} 的腰！”,
    “{user1} 戳了 {user2}！”,
    “{user1} 用针戳了 {user2}！”,
    “{user1} 用笔戳了 {user2}！”,
    “{user1} 用电棍戳了 {user2}！”,
    “{user2} 其实是个兽迷！”,
    “大家注意！{user1} 在叫我使坏！”,
    “( ･_･)ﾉ⌒●~* (･.･;) <-{user2}”,
    “吃我这招 {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* “,
    “{user2} 接好了\n(｀・ω・)つ ●~＊”,
    “( ・_・)ノΞ●~*  {user2}\n去死吧！！”,
    “( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*对 {user2} 喷了杀虫剂*。”,
    “( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} 你这害虫！”,
    “( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}。”,
    “{user1} 用 {item} {hits} 了 {user2}。”,
    “{user1} 用 {item} {hits} 了 {user2} 的脸。”,
    “{user1} 用 {item} 随手 {hits} 了 {user2}。”,
    “{user1} 向 {user2} {throws} 了一个 {item}。”,
    “{user1} 抓起 {item} 向 {user2} 的脸 {throws} 了过去。”,
    “{user1} 朝 {user2} 的大致方向 {throws} 了一个 {item}。”,
    “{user1} 用 {item} 把 {user2} 拍得晕头转向。”,
    “{user1} 把 {user2} 压在地上，用 {item} 反复 {hits}。”,
    “{user1} 抢来 {item} 用它 {hits} 了 {user2}。”,
    “{user1} 把 {user2} 绑在椅子上，向他 {throws} 了个 {item}。”,
    “{user1} 友善地推了 {user2} 一把，帮他学会了在岩浆里游泳。”,
    “{user1} 欺负了 {user2}。”,
    “Nyaan 吃了 {user2} 的腿。*咔嚓咔嚓*”,
    “{user1} 向 {user2} {throws} 了一个超级球，无从逃脱。”,
    “{user1} 用必杀光束打了 {user2}……bbbbbb (ง・ω・)ง ====*”,
    “{user1} 对 {user2} 发出了阿啦啦。”,
    “{user1} 对 {user2} 发出了嗷嗷嗷。”,
    “{user1} 对 {user2} 发出了无驾驾。”,
    “{user2} 被变成了 Jojo 的梗！”,
    “{user1} 用 {item} 打了 {user2}。”,
    “第二回合！准备好了吗？……格斗！！”,
    “WhoPixel 要把 {user2} 送到无限远和更远处。”,
    “{user2} 吃了蝙蝠并发现了一种新疾病。”,
    “{user1} 把 {user2} 折成了纸飞机”,
    “{user1} 给 {user2} 端上了一碗蝙蝠汤。”,
    “{user2} 被送回了他的家园——猿人星球。”,
    “{user1} 把 {user2} 踢下了行驶中的列车。”,
    “{user2} 刚杀了 John Wick 的狗。”,
    “{user1} 对 {user2} 施了阿瓦达索命咒。”,
    “{user1} 把 {user2} 扔进了烈火熔炉。”,
    “春野樱刚刚变得比 {user2} 更有用了”,
    “{user1} 拔掉了 {user2} 的生命维持设备。”,
    “{user1} 让 {user2} 订阅了五年的龟速网络。”,
    “你知道什么比老爸笑话还糟糕吗？{user2}！”,
    “{user1} 抢走了 {user2} 所有的饼干。”,
    “{user2} 已经……死了！——{user1}。”,
    “{user2} 输掉了他的国家棋！”,  # No game no life reference
    “闭嘴 {user2}，你就是个 {user2}。”,  # No game no life reference
    “{user1} 用 Aka si anse 打了 {user2}！”,  # No game no life reference
    “@NeoTheKitty 抓了 {user2}”,  # Pixels pet cat - @NeoTheKitty
    “魔人布欧吃了 {user2}”,  # Dbz
    “哥布林杀手消灭了 {user2}”,  # Goblin Slayer
)

PAT_TEMPLATES = (
    “{user1} 摸了摸 {user2} 的头。”,
    “*轻柔地揉了揉 {user2} 的头*。”,
    “*{user1} 软软地摸了摸 {user2} 的头*”,
    “*{user1} 弄乱了 {user2} 的头发*”,
    “*{user1} 使劲揉了揉 {user2} 的头*”,
    “*{user2} 的老婆摸了摸他们的头*”,
    “*{user2} 获得了免费摸头服务*”,
    “{user2} 没有摸头！”,
    “哦不！我们的摸头配额用完了。”,
    “这里是禁止摸头区！”,
    “{user2} 没有摸头！”,
    “{user1} 用摸头把 {user2} 宠坏了！”,
    “{user2} 获得了一次免费摸头！”,
    “{user1} 摸着 {user2} 的头，还给他枕大腿”,
    “{user1} 凶猛地摸了摸 {user2}”,
    “{user1} 轻柔地抚摸了 {user2} 的头”,
    “摸，摸，摸，摸”,
    “{user2} 无法逃脱 {user1} 的摸头攻势”,
    “{user2}.exe 已停止运行”,
    “{user1} 揉了揉 {user2} 的脖子”,
    “必须……索取……摸头！”,
    “{user1} 摸了一下 {user2} 的头”,
    “{user1} 突然摸了 {user2}”,
    “{user1} 征得同意后摸了 {user2}，也许吧？”,
    “摸摸，{user2} 本当可愛いね！”,
    “{user1} 以 420apm 的速度摸了 {user2}”,
    “{user1} 揉了揉 {user2} 的肚子”,
    “{user1} 友好地摸了摸 {user2}”,
    “{user2} 用了摸头？哦可爱こと”,
    “*headpats.gif 为 {user2} 持续加速*”,
    “(*´ω´(*｀ω｀)”,
    “(ｏ・_・)ノ”(ᴗ_ ᴗ。)”,
    “(*￣▽￣)ノ”(- -*)”,
    “(っ´ω`)ﾉ(╥ω╥)”,
    “( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ”,
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = ("ɪ ᴀᴍ ᴀʟɪᴠᴇ ʙᴀʙʏ! 🖤",)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("Heads", "Tails")

EIGHTBALL = [
    "🟢 As I see it, yes.",
    "🟡 Ask again later.",
    "🟡 Better not tell you now.",
    "🟡 Cannot predict now.",
    "🟡 Concentrate and ask again.",
    "🟡 Don’t count on it.",
    "🟢 It is certain.",
    "🟢 It is decidedly so.",
    "🟢 Most likely.",
    "🔴 My reply is no.",
    "🔴 My sources say no.",
    "🔴 Outlook not so good.",
    "🟢 Outlook good.",
    "🟡 Reply hazy, try again.",
    "🟢 Signs point to yes.",
    "🔴 Very doubtful.",
    "🟢 Without a doubt.",
    "🟢 Yes.",
    "🟢 Yes – definitely.",
    "🟢 You may rely on it.",
]

DECIDE = ("Yes.", "No.", "Maybe.")

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "I ran out of tables, will order more.",
    "Go do some work instead of flippin tables.",
)
